[build]
  command = "NODE_OPTIONS=--openssl-legacy-provider npm run build"
  publish = "build"

[build.environment]
  NODE_VERSION = "18.17.0"
  NPM_FLAGS = "--production=false"
  NODE_OPTIONS = "--openssl-legacy-provider"

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200
